config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    passwords: "users/passwords",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  # resources :static_pages
  root "static_pages#top"
  get "/terms" => "static_pages#terms"
  get "/privacy_policy" => "static_pages#privacy_policy"
  get "/contact" => "static_pages#contact"

  get "/mypage" => "users#mypage", as: :mypage

  resources :users, only: %i[show]

  resources :questions, only: %i[index new create show edit update destroy] do
    resources :card_sets,  only: %i[new create edit update destroy] do
      resources :related_words,  only: %i[new create edit update destroy]
    end
    resource :list_questions, only: %i[create destroy] do
      patch :update_multiple, on: :collection
    end
    collection do
      get :autocomplete
    end
  end

  resources :games, only: [ :show ] do
    member do
      post :check_match
    end
  end

  resources :game_records, only: %i[create show] do
    collection do
      get :batch_results
    end
  end
  resources :requests, only: %i[index new create show] do
    resources :request_responses, only: %i[create], shallow: true
  end

  resources :lists, only: %i[new create edit update destroy] do
    member do
      get :batch_play
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest


  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name, presence: true, length: { maximum: 20 }
  validates :bio, length: { maximum: 150 }, allow_blank: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :timeoutable,
         :omniauthable, omniauth_providers: %i[google_oauth2]

  has_many :sns_credential, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :game_records, dependent: :destroy
  has_many :requests, dependent: :destroy
  has_many :request_responses, dependent: :destroy
  has_many :lists, dependent: :destroy
  has_many :list_questions, through: :lists
  has_many :liked_questions, through: :list_questions, source: :question

  after_validation :replace_email_taken_error

  class << self   # ここからクラスメソッドで、メソッドの最初につける'self.'を省略できる
    # SnsCredentialsテーブルにデータがないときの処理
    def without_sns_data(auth)
      user = User.where(email: auth.info.email).first

      if user.present?
        sns = SnsCredential.create(
          uid: auth.uid,
          provider: auth.provider,
          user_id: user.id
        )
      else   # User.newの記事があるが、newは保存までは行わないのでcreateで保存をかける
        user = User.create(
          name: auth.info.name,
          email: auth.info.email,
          # profile_image: auth.info.image,    # プロフ画像も取り込む場合はコメント解除
          password: Devise.friendly_token(10)   # 10文字の予測不能な文字列を生成する
        )
        sns = SnsCredential.create(
          user_id: user.id,
          uid: auth.uid,
          provider: auth.provider
        )
      end
      { user:, sns: }   # ハッシュ形式で呼び出し元に返す
    end

    # SnsCredentialsテーブルにデータがあるときの処理
    def with_sns_data(auth, snscredential)
      user = User.where(id: snscredential.user_id).first
      # 変数userの中身が空文字, 空白文字, false, nilの時の処理
      if user.blank?
        user = User.create(
          name: auth.info.name,
          email: auth.info.email,
          profile_image: auth.info.image,
          password: Devise.friendly_token(10)
        )
      end
      { user: }
    end

    # Googleアカウントの情報をそれぞれの変数に格納して上記のメソッドに振り分ける処理
    def find_oauth(auth)
      uid = auth.uid
      provider = auth.provider
      snscredential = SnsCredential.where(uid:, provider:).first
      if snscredential.present?
        user = with_sns_data(auth, snscredential)[:user]
        sns = snscredential
      else
        user = without_sns_data(auth)[:user]
        sns = without_sns_data(auth)[:sns]
      end
      { user:, sns: }
    end
  end

  def own?(object)
    id == object&.user_id
  end

  # お気に入りリスト取得（なければ自動生成しても良い）
  def favorite_list
    lists.find_or_create_by!(is_favorite: true) do |list|
      list.name = "お気に入り"
    end
  end

  private

  def replace_email_taken_error
    if errors.details[:email]&.any? { |d| d[:error] == :taken }
      # 既存のすべてのエラーをクリア
      errors.clear
      # baseエラーとして追加（属性名が前に付かない）
      errors.add(:base, "登録できませんでした。入力内容をご確認ください")
    end
  end

  def self.ransackable_attributes(auth_object = nil)
    [ "name" ]
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]
  def google_oauth2
    callback_for(:google)
  end

  def callback_for(provider)
    @omniauth = request.env["omniauth.auth"]
    info = User.find_oauth(@omniauth)
    @user = info[:user]
    if @user.persisted?    # persisted?は保存が完了しているかを評価するメソッド
      sign_in_and_redirect @user, event: :authentication
      # is_navigational_formatはフラッシュメッセージを発行する必要があるかどうかを確認する
      # capitalizeは文字列の先頭を大文字に、それ以外は小文字に変更して返すメソッド
      set_flash_message(:notice, :success, kind: provider.to_s.capitalize) if is_navigational_format?
    else
      @sns = info[:sns]
      render template: "devise/registrations/new"
    end
  end


  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  def failure
    redirect_to root_path
    set_flash_message(:notice, :failure, kind: "Google") if is_navigational_format?
  end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [ :create ]
  before_action :configure_account_update_params, only: [ :update ]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # We need to use a copy of the resource because we don't want to change
  # the current user in place.
  def update
    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
    prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)

    resource_updated = update_resource(resource, account_update_params)
    yield resource if block_given?
    if resource_updated
      set_flash_message_for_update(resource, prev_unconfirmed_email)
      bypass_sign_in resource, scope: resource_name if sign_in_after_change_password?

      respond_with resource, location: after_update_path_for(resource)
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
    current_user.reload
  end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :name ])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [ :name, :bio ])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    root_path
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    root_path
  end

  protected
  # パスワードなしでユーザー情報を更新
  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  # 編集後のリダイレクト先を指定するメソッド
  def after_update_path_for(resource)
    params[:redirect_to] || mypage_path(resource)
  end

  private

  def set_flash_message_for_update(resource, prev_unconfirmed_email)
    return unless is_flashing_format?

    flash_key = if update_needs_confirmation?(resource, prev_unconfirmed_email)
      :update_needs_confirmation
    elsif sign_in_after_change_password?
      :updated
    else
      :updated_but_not_signed_in
    end
    set_flash_message :notice, flash_key
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [ :create ]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [ :attribute ])
  end

  # サインイン後のリダイレクト先を指定する
  def after_sign_in_path_for(resource)
    root_path
  end

  # サインアウト後のリダイレクト先を指定
  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include Filterable

  before_action :authenticate_user!, except: %i[ show ]
  before_action :set_selected_user, only: %i[ show ]
  before_action :set_user, only: %i[ mypage ]
  before_action :set_questions, only: %i[ show mypage ]
  before_action :set_calender_data, only: %i[ show mypage ]

  def show;  end

  def mypage
    # クッキーに設定を保存
    save_filter_understood_preference

    # プレイ履歴のフィルタリング
    game_records_query = @user.game_records.includes(:question).order(created_at: :desc)
    game_records_query = apply_understood_filter_to_records(game_records_query, @user)
    @game_records = game_records_query.page(params[:game_records_page]).per(10)

    # ユーザーの全リストを取得（お気に入りと通常リストを分けて結合）
    favorite_lists = @user.lists.where(is_favorite: true)
    normal_lists = @user.lists.where(is_favorite: false).order(updated_at: :desc)
    @lists = favorite_lists + normal_lists

    # 選択されたリスト（デフォルトはお気に入り）
    @selected_list_id = params[:list_id] || @user.favorite_list.id
    @list = @lists.find { |list| list.id == @selected_list_id.to_i } || @user.favorite_list

    # リストの問題をリスト追加降順で取得（フィルタリング適用）
    list_questions_query = @list.questions.with_tag_relations.order("list_questions.created_at DESC")
    list_questions_query = apply_understood_filter(list_questions_query, @user)
    @list_questions = list_questions_query

    @current_tab = params[:tab] || "user_questions"
  end

  private

  def set_selected_user
    @user = User.find(params[:id])
  end

  def set_user
    @user = current_user
  end

  def set_questions
    @questions = @user.questions.includes(:category, :tags).page(params[:questions_page]).order(updated_at: :desc)
  end

  def set_calender_data
    # カレンダーチャート用のデータを作成
    @calendar_data = build_calendar_data
  end

  def build_calendar_data
    # 問題追加数を日毎に集計
    questions_by_date = @user.questions
    .group("DATE(created_at)")
    .count

    # game_recordsを日毎に集計
    game_records_by_date = @user.game_records
    .group("DATE(created_at)")
    .count

    # 2つのハッシュをマージして、日付毎の合計値を計算
    merged_data = questions_by_date.merge(game_records_by_date) do |date, questions_count, records_count|
      questions_count + records_count
    end

    # カレンダーチャート用のフォーマットに変換 [[Date, count], ...]
    merged_data.map do |date_str, count|
      [ date_str.to_date, count ]
    end
  end
end

app/views/users/_calender_chart.html.erb
<div class="flex">
  <h3 class="font-semibold mb-2">学習カレンダー</h3>
  <div class="badge badge-soft badge-xs badge-info ml-2 tooltip before:ml-4", data-tip="問題作成または問題プレイで色が濃くなります">?</div>
</div>
<%= calendar_chart(
          {
            data: @calendar_data
          },
          class: '',
          style: 'height: 130px; width: 300px;',
          options: {
            grid: {
              top: 10,
              bottom: 10,
              left: 40,
              right: 40
            },
            visualMap: {
              show: false,
              min: 0,
              max: 40,
              inRange: {
                color: ['#DAFADA', '#008000']
              }
            },
            calendar: [
              {
                range: ["#{2.month.ago.strftime('%Y-%m-%d')}", "#{Date.today.strftime('%Y-%m-%d')}"],
                top: 20,
                left: 50,
                right: 20,
                cellSize: [13],
                yearLabel: { show: true },
                monthLabel: {
                  margin: 1,
                  show: true,
                  formatter: '{M}月'
                },
                dayLabel: {
                  margin: 2,
                  firstDay: 1,
                  nameMap: ['日', '月', '火', '水', '木', '金', '土']
                },
                splitLine: {
                  lineStyle: {
                    color: '#793205',
                    width: 0.5
                  }
                }
              }
            ]
          })
        %>

app/views/users/_list_questions.html.erb
<% @list_id = list_id %>
<div class="grid sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-12 mx-auto max-w-screen-6xl pb-8 items-stretch">
  <% if list_questions.present? %>
    <%= render partial: "list_questions/question", collection: list_questions, as: :question %>
  <% else %>
    <div class="m-8">問題がありません</div>
  <% end %>
</div>

app/views/users/_list_selector.html.erb
<%= select_tag :list_id,
               options_for_select(lists.map { |list| [list.name, list.id, { "data-is-favorite" => list.is_favorite }] }, selected_list_id),
               class: "select select-bordered w-full max-w-xs",
               id: "list_id",
               data: {
                 list_selector_target: "select",
                 action: "change->list-selector#changeList"
               } %>

app/views/users/_mypage_user_questions.html.erb
<%= paginate @questions, param_name: :questions_page, params: { tab: 'user_questions' } %>
<div class="grid sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-12 mx-auto max-w-screen-6xl py-8 items-stretch">
  <%= render 'user_questions' %>
</div>
<%= paginate @questions, param_name: :questions_page, params: { tab: 'user_questions' } %>

app/views/users/_profile.html.erb
<div class="flex items-center mb-2">
  <h1 class="text-2xl font-bold"><%= @user.name %></h1>
  <% if @user == current_user %>
    <%= link_to edit_user_registration_path(redirect_to: redirect_path), class: "btn btn-outline btn-success btn-sm ml-3" do %>
      <i class="fa-solid fa-pen"></i>
    <% end %>
  <% end %>
</div>

<% if @user.bio.present? %>
  <p class="text-sm text-base-content/80 whitespace-break-spaces mb-6"><%= @user.bio %></p>
<% end %>
  

app/views/users/_user_questions.html.erb
<% if @questions.present? %>
  <%= render @questions %>
<% else %>
  <div class="m-8">問題がありません</div>
<% end %>

app/views/users/_userpage_user_questions.html.erb
<%= paginate @questions, param_name: :questions_page, params: { tab: 'user_questions' } %>
<div class="grid sm:grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-12 mx-auto max-w-screen-6xl py-8 items-stretch">
  <%= render 'user_questions' %>
</div>
<%= paginate @questions, param_name: :questions_page, params: { tab: 'user_questions' } %>

app/views/users/mypage.html.erb
<% breadcrumb :mypage %>
<div class="flex flex-col pt-6 <%= "#{'lg:flex-row' if @user.bio.present?}" %> gap-4 px-4">
  <div class="w-full  <%= "#{'lg:w-auto lg:h-full' if @user.bio.present?}" %> ">
    <div class="card bg-base-100 card-xs px-3">
      <div class="card-body">
        <%= render "profile", redirect_path: mypage_path %>
      </div>
    </div>
  </div>
  <div class="<%= "#{'lg:pt-3' if @user.bio.present?}" %> lg:pl-6">
      <div class="card-body">
    <%= render 'calender_chart' %>
  </div>
  </div>
</div>

<div class="tabs tabs-lift mt-3 p-4">
  <%= link_to mypage_path(tab: 'user_questions'),
              class: "tab #{'tab-active' if @current_tab == 'user_questions'}",
              role: 'tab',
              aria: { label: t('.user_questions') } do %>
    <%= t('.user_questions') %>
  <% end %>
  <div class="tab-content bg-base-100 border-base-300 p-6 <%= 'hidden' unless @current_tab == 'user_questions' %>">
    <%= render 'mypage_user_questions' %>
  </div>

  <%= link_to mypage_path(tab: 'user_lists', list_id: @list.id),
              class: "tab #{'tab-active' if @current_tab == 'user_lists'}",
              role: 'tab',
              aria: { label: t('.user_lists') } do %>
    <%= t('.user_lists') %>
  <% end %>
  <div class="tab-content bg-base-100 border-base-300 p-6 <%= 'hidden' unless @current_tab == 'user_lists' %>" data-controller="list-selector">
    <div class="flex">
      <div id="list_selector_container" class="mb-2">
        <%= render "list_selector", lists: @lists, selected_list_id: @list.id %>
      </div>

      <div class="dropdown dropdown-end">
        <div tabindex="0" role="button" class="btn btn-ghost"><i class="fa-solid fa-ellipsis-vertical"></i></div>
        <ul tabindex="-1" class="dropdown-content menu bg-gradient-to-br from-base-100 to-base-200 rounded-box z-1 w-52 p-2 shadow-sm">
          <div class="<%= 'hidden' if @list.is_favorite %>" >

            <li>
              <%= link_to edit_list_path(@list), data: { turbo_frame: "modal" } do %>
                <i class="fa-solid fa-pen text-success/70" aria-hidden="true"></i>
                リスト名を変更
              <% end %>
            </li>

            <li>
              <%= link_to @list, class: "text-warning", data: {turbo_method: :delete, turbo_confirm: t('defaults.delete_confirm') } do %>
                 <i class="fa-solid fa-trash text-warning/70" aria-hidden="true"></i>
                  このリストを削除
              <% end %>
            </li>
          </div>

          <li>
            <%= link_to new_list_path(list_id: @list.id), data: { turbo_frame: "modal" } do %>
              <i class="fa-solid fa-plus text-error" aria-hidden="true"></i>
              新規リストを作成
            <% end %>
          </li>

        </ul>
      </div>
    </div>

    <%= render 'shared/filter_out_understood_questions' %>

    <% if @list_questions.present? %>
      <%= link_to batch_play_list_path(@list), class: "btn btn-secondary mt-2 mb-4" do %>
        <i class="fa-solid fa-play"></i>
        このリストをまとめてプレイ
      <% end %>
    <% end %>

    <%= turbo_frame_tag "list_questions" do %>
      <%= render partial: "users/list_questions", locals: { list_questions: @list_questions, list_id: @list.id } %>
    <% end %>
  </div>

  <%= link_to mypage_path(tab: 'game_records'),
              class: "tab #{'tab-active' if @current_tab == 'game_records'}",
              role: 'tab',
              aria: { label: t('.game_records') } do %>
    <%= t('.game_records') %>
  <% end %>
  <div class="tab-content bg-base-100 border-base-300 p-6 <%= 'hidden' unless @current_tab == 'game_records' %>">

        <div class="mb-2">
          <%= render 'shared/filter_out_understood_questions' %>
        </div>
        <!--%= render 'game_records/game_records' %-->
        <% if @game_records.present? %>
          <%= paginate @game_records, param_name: :game_records_page, params: { tab: 'game_records' } %>
            <%= render 'game_records/game_record' %>
          <div class="p-6">
            <%= paginate @game_records, param_name: :game_records_page, params: { tab: 'game_records' } %>
          </div>
        <% else %>
          <div class="m-8">履歴がありません</div>
        <% end %>

  </div>
</div>

<%= turbo_frame_tag "modal" %>

app/views/users/show.html.erb
<% breadcrumb :user_show, @user %>
<div class="container mx-auto px-4 py-8">
  <div class="grid grid-cols-1 lg:grid-cols-12 lg:px-12 gap-6">
    <!-- 左カラム: ユーザー情報とカレンダー -->
    <div class="lg:col-span-4 xl:col-span-3 lg:mt-12">
      <!-- ユーザー情報 -->
      <%= render "profile", redirect_path: user_path(@user) %>

      <%= render 'calender_chart' %>
    </div>

    <!-- 右カラム: 作成した問題 -->
    <div class="lg:col-span-8 xl:col-span-9">
      <div class="card bg-base-100 border-2 border-current/10">
        <div class="card-body">
          <h2 class="text-xl font-bold mb-4">
            作成した問題
          </h2>

          <!-- 問題リスト -->
          <div class="space-y-4">
            <%= render 'userpage_user_questions' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>