config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    passwords: "users/passwords",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  # resources :static_pages
  root "static_pages#top"
  get "/terms" => "static_pages#terms"
  get "/privacy_policy" => "static_pages#privacy_policy"
  get "/contact" => "static_pages#contact"

  get "/mypage" => "users#mypage", as: :mypage

  resources :users, only: %i[show]

  resources :questions, only: %i[index new create show edit update destroy] do
    resources :card_sets,  only: %i[new create edit update destroy] do
      resources :related_words,  only: %i[new create edit update destroy]
    end
    resource :list_questions, only: %i[create destroy] do
      patch :update_multiple, on: :collection
    end
    collection do
      get :autocomplete
    end
  end

  resources :games, only: [ :show ] do
    member do
      post :check_match
    end
  end

  resources :game_records, only: %i[create show] do
    collection do
      get :batch_results
    end
  end
  resources :requests, only: %i[index new create show] do
    resources :request_responses, only: %i[create], shallow: true
  end

  resources :lists, only: %i[new create edit update destroy] do
    member do
      get :batch_play
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest


  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :question
  belongs_to :user

  has_many :request_responses, dependent: :destroy

  validates :title, presence: true, length: { maximum: 60 }
  validates :content, presence: true, length: { maximum: 500 }

  enum status: { incompleted: 0, completed: 1 }

  # Runsackホワイトリスト
  def self.ransackable_attributes(auth_object = nil)
    [ "title", "content", "status" ]
  end

  def self.ransackable_associations(auth_object = nil)
    [ "user", "question" ]
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :authenticate_user!, except: %i[ index show ]

  def index
    # 検索条件がない場合はデフォルトで未完了のみ表示
    search_params = params[:q] || {}

    # 初回アクセス（検索条件が空）の場合は未完了のみ表示
    if search_params.empty?
      search_params[:status_in] = [ "0" ]
    end

    @search_request = Request.ransack(search_params) # ransackメソッド推奨
    @search_requests = @search_request.result(distinct: true).includes(:user, :question, { question: :user }, { request_responses: :user }).order(created_at: :desc).page(params[:page])
    @current_requests_tab = params[:tab] || "requests"
  end

  def new
    @request = Request.new
    @search = Question.ransack(params[:q])
  end

  def create
    @request = current_user.requests.build(request_params)
    if @request.save
      redirect_to request_path(@request), notice: t("defaults.flash_message.created", item: Request.model_name.human)
    else
      flash.now[:alert] = t("defaults.flash_message.not_created", item: Request.model_name.human)
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @request = Request.find(params[:id])
    @request_response = RequestResponse.new
    @request_responses = @request.request_responses.includes(:user).order(created_at: :asc)
    @latest_request_response = @request_responses.last
  end

  private

  def request_params
    params.require(:request).permit(:title, :content, :question_id)
  end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_incompleted_request_btn.html.erb
<div class="tooltip" data-tip="<%= t('.check_request') %>">
  <%= link_to t('.incompleted'), requests_path(q: { question_title_cont: question.title, status_in: ['0'] }), class: "btn btn-warning w-full sm:w-auto" %>
</div>

app/views/requests/_question_search_form.html.erb
<div data-controller="autocomplete request-form"
      data-autocomplete-url-value="<%= autocomplete_questions_path %>"
      data-autocomplete-hidden-field="#request_question_id">
  <input class="input input-bordered w-full"
         autocomplete="off"
         data-autocomplete-target="input"
         type="search" />
  <ul class="list-group" data-autocomplete-target="results"></ul>
</div>

app/views/requests/_request.html.erb
<%
  tab_type = local_assigns[:tab_type]
  
  # タブに応じてフィルタリングした修正依頼を取得
  filtered_requests = @search_requests.select do |request|
    case tab_type
    when 'requests_to_user'
      request.question.user == current_user
    when 'requests_from_user'
      request.user == current_user
    else # 'requests'
      true
    end
  end
%>

<% if filtered_requests.present? %>
  <%= paginate @search_requests, param_name: :requests_page, params: { tab: 'requests' } %>
  <% filtered_requests.each do |request| %>
    <div id="request-id-<%= request.id %>">
      <div class="p-2">
        <ul class="list-inside bg-base-100 rounded-box shadow-md p-4">
          <li class=" grid grid-cols-1 gap-4 m-2">
            <div class="col-start-1 col-span-1">
              <div class="flex items-center">
                <div><%= render 'requests/status_badge', request: request %></div>
                <%= link_to request.title, request_path(request), class: "link ml-2" %>
              </div>
              <div class="text-sm">
                <div class="flex ml-20">
                  <p class="min-w-max"><%= t('.request_user') %></p>
                  <div class="ml-2" ><%= request.user.name %></div>
                </div>
                  <p class="ml-20">
                  <%= link_to "#{request.question.title}  by #{request.question.user.name}", question_path(request.question), class: "link" %>
                  </p>
              </div>
            </div>
            <div class="col-start-1 col-span-1">
              <div class="text-sm">
                <% if request.request_responses.present? %>
                  <div class="flex pt-2">
                    <p class="min-w-max"><%= t('.last_response_user') %></p>
                    <div class="ml-2"><%= request.request_responses.last.user.name %></div>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="col-start-1 col-span-1">
              <div class="text-sm">
                <div class="flex justify-end">
                  <%= t('.created_at') %>
                  <%= l request.created_at, format: :short %>
                </div>
              </div>
            </div>
          </li>
        </ul>
      </div>
    </div>
  <% end %>
<% else %>
  <div class="m-8"><%= t('requests.index.requests_empty') %></div>
<% end %>

app/views/requests/_request_btn.html.erb
<%= link_to t('.request'), new_request_path, class: "btn btn-accent w-full sm:w-auto" %>

app/views/requests/_search_form.html.erb
<div class="card w-93 bg-base-100 card-xs shadow-sm px-3">
  <div class="card-body">
    <%= search_form_for @search_request, url: requests_path do |f| %>
      <div class="mb-4">
        <label class="input flex items-center w-auto">
          <svg class="h-[1em] opacity-50 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
            <g stroke-linejoin="round" stroke-linecap="round" stroke-width="2.5" fill="none" stroke="currentColor">
              <circle cx="11" cy="11" r="8"></circle>
              <path d="m21 21-4.3-4.3"></path>
            </g>
          </svg>
          <%= f.search_field :title_or_question_title_or_content_or_user_name_cont, placeholder: t('.placeholder'), class: "sm:w-64 md:w-64" %>
        </label>
        <div class="flex gap-4 mt-2">
          <% Request.statuses.each do |key, value| %>
            <% 
              # デフォルトは未完了のみ選択、検索後は検索条件を保持
              checked = if params[:q] && params[:q][:status_in]
                          params[:q][:status_in].include?(value.to_s)
                        else
                          key == 'incompleted'
                        end
            %>
            <%= check_box_tag "q[status_in][]", value, checked, class: "checkbox", id: "status_#{key}" %>
            <label for="status_<%= key %>" class="text-base">
              <%= t("activerecord.enums.request.status.#{key}") %>
            </label>
          <% end %>
        </div>
        <div class="justify-end card-actions">
          <%= f.submit t('defaults.search'), class: "btn btn-outline mt-2" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/requests/_status_badge.html.erb
<% case request.status %>
<% when 'incompleted' then %>
  <div class="badge badge-warning"><%= t('.incompleted') %></div>
<% when 'completed' then %>
  <div class="badge badge-success"><%= t('.completed') %></div>
<% end %>

app/views/requests/index.html.erb
<% breadcrumb :requests_index %>
<h1 class="text-2xl font-bold text-left p-6"><%= t('.title') %></h1>
<div class="md:justify-self-start">
  <div class="max-w-3xl mx-auto px-4">
    <%= render 'search_form' %>
  </div>
</div>
<div class="p-6">
  <%= render 'requests/request_btn' %>
</div>

<% if user_signed_in? %>
  <div class="tabs tabs-lift mt-3 p-4">
    <%= radio_button_tag 'my_tabs_3', 'requests_to_user', @current_requests_tab == 'requests_to_user',
                      class: 'tab',
                      aria: { label: t('.requests_to_user') } %>
    <div class="tab-content bg-base-100 border-base-300 p-6">
      <% if @search_requests.present? %>
        <%= render 'requests/request', tab_type: 'requests_to_user' %>
      <% else %>
        <div class="m-8"><%= t('.requests_empty') %></div>
      <% end %>
    </div>

    <%= radio_button_tag 'my_tabs_3', 'requests', @current_requests_tab == 'requests',
                      class: 'tab',
                      aria: { label: t('.requests') } %>
    <div class="tab-content bg-base-100 border-base-300 p-6">
      <!--%= render 'requests/requests' %-->
      <% if @search_requests.present? %>
        <%= render 'requests/request', tab_type: 'requests' %>
      <% else %>
        <div class="m-8"><%= t('.requests_empty') %></div>
      <% end %>
    </div>

    <%= radio_button_tag 'my_tabs_3', 'requests_from_user', @current_requests_tab == 'requests_from_user',
                      class: 'tab',
                      aria: { label: t('.requests_from_user') } %>
    <div class="tab-content bg-base-100 border-base-300 p-6">
      <% if @search_requests.present? %>
        <%= render 'requests/request', tab_type: 'requests_from_user' %>
      <% else %>
        <div class="m-8"><%= t('.requests_empty') %></div>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="p-3">
    <ul class="list bg-base-100 rounded-box shadow-md">
      <% if @search_requests.present? %>
        <%= render 'requests/request', tab_type: 'requests' %>
      <% else %>
        <div class="m-8"><%= t('.requests_empty' )%></div>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/requests/new.html.erb
<div class="container mx-auto px-4 py-8">
  <div class="grid grid-cols-1 lg:grid-cols-8">
    <% breadcrumb :requests_new %>
    <div class="lg:col-start-2 lg:col-span-6">
      <div class="card bg-base-100 shadow-lg p-4">
      <h1 class="text-2xl font-bold text-left px-6 pt-6"><%= t('.title') %></h1>
      <%= link_to t('.to_index'), requests_path, class: "link pt-2 pl-6 text-sm" %>
        <div class="card-body">
          <%= form_with model: @request, class: "new_request", local: true do |f| %>
            <%= render 'shared/error_messages', object: f.object %>

            <div class="form-control mb-4">
              <%= f.label :question_title %>
              <div class="text-xs text-base-content/70">
                <%= t('.description') %>
              </div>
              <%= render 'requests/question_search_form' %>
              <%= f.hidden_field :question_id %>
            </div>
            <div class="form-control mb-4">
              <%= f.label :title %>
              <%= f.text_field :title, class: "input input-bordered w-full" %>
            </div>
            <div class="form-control mb-6">
              <%= f.label :content%>
              <%= f.text_area :content, class: "textarea textarea-bordered w-full", rows: "10" %>
            </div>
            <div class="card-actions justify-end">
              <%= f.submit t('.post'), class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/requests/show.html.erb
<div class="container mx-auto px-4 py-8">
  <% breadcrumb :requests_show, @request %>
  <div class="grid grid-cols-1 lg:grid-cols-8">
    <div class="lg:col-start-2 lg:col-span-6">
      <div class="card bg-base-100 shadow-lg p-6">
      <%= link_to t('.to_index'), requests_path, class: "link" %>
        <div class="flex items-center pt-4">
          <div><%= render 'requests/status_badge', request: @request %></div>
          <h1 class="text-2xl font-bold text-left px-2"><%= @request.title %></h1>
        </div>
        <div class="card-body">
          <ul class="pl-2 text-sm">

            

            <li class="pb-2"><%= t('.question') %><%= link_to "#{@request.question.title}  by #{@request.question.user.name}", question_path(@request.question), class: "link" %></li>
            <li><%= t('.request_user') %><%= @request.user.name %></li>
            <li class="pb-2"><%= t('.created_at') %><%= l @request.created_at, format: :long %></li>
            <% if @latest_request_response %>
              <li><%= t('.last_response_user') %><%= @latest_request_response.user.name %></li>
              <li><%= t('.last_response_created_at') %><%= l @latest_request_response.created_at, format: :long %></li>
            <% end %>
          </ul>
        </div>
          <h5 class="text-lg font-semibold pl-6 mb-2"><%= t('.content') %></h5>
          <div class="pl-6">
            <p><%= simple_format(@request.content) %></p>
          </div>
          <h5 class="text-lg font-semibold pl-6 mt-6 mb-2"><%= t('.responses') %></h5>
          <div class="pl-2">
            <%= render @request_responses %>
              <% if @request.status != "completed" %>
                <% if user_signed_in? %>
                 <%= render 'request_responses/form', request_response: @request_response, request: @request %>
                <% else %>
                  <span class="label-text ml-2"><%= t('.require_login') %></span>
                <% end %>
              <% else %>
                <div class="request-response-closed-message bg-accent">
                  <%= t('.closed') %>
                </div>
              <% end %>
          </div>
      </div>
    </div>
  </div>
</div>